spring:
  application:
    name: profile-app
  profiles:
    active: local

eureka:
  client:
    enabled: true
    port: 0
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    lease-renewal-interval-in-seconds: 30
    appname: profile